### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Zackmon** [TheLastRar/CLR-USB#1]
is it possible to support Linux ?
or if you have some hints on how to port this to linux

**Comment by TheLastRar** [comment]
This doesn't support Linux

Supporting Linux would require a native wrapper layer to be developed similar to CLR_DEV9 (which uses mono) or a cross platform version of DllExport (I believe one exists for .net core?)

A linux compatible back end would also need to be written, as both back ends present uses windows APIs directly

Regarding a keyboard plugin for Linux, I believe later versions of USBQemu-wheel (https://github.com/jackun/USBqemu-wheel/releases) should be suitable

If there are any features of CLR-DEV9 that USBQemu-wheel is missing let me know, I haven't recently compared the two
